### ISSUE TITLE
reading from a string instead of open a file?

### ISSUE THREAD

**Issue by beedaddy** [mitchmindtree/m3u#6]
I don't know if this is a feature request or if I just don't know how to do this (in that case: sorry for the stupid question). But I would like to not open a local file but to parse a string (which has been retrieved from a url). So, can m3u::Reader somehow read from a string instead of open a file?

**Comment by mitchmindtree** [comment]
Hey, it should be possible to construct either an `EntryReader` or `EntryExtReader` with whatever `Read` type you like using the `new` or `new_ext` constructors. E.g. [the `open` method does this](https://docs.rs/m3u/1.0.0/src/m3u/read.rs.html#258) with a `BufReader`. Hope this helps!

**Comment by beedaddy** [comment]
Thanks a lot!
